# Generated by Django 5.0.1 on 2025-05-15 07:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='data_sources/')),
                ('file_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('graph_type', models.CharField(choices=[('line', 'Line Chart'), ('bar', 'Bar Chart'), ('scatter', 'Scatter Plot'), ('pie', 'Pie Chart'), ('histogram', 'Histogram'), ('box', 'Box Plot'), ('heatmap', 'Heat Map'), ('bubble', 'Bubble Chart'), ('area', 'Area Chart'), ('radar', 'Radar Chart')], max_length=50)),
                ('configuration', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='data_processor.datasource')),
            ],
        ),
    ]
